### ISSUE TITLE
Fail to build docs: AttributeError: module 'bibtexparser' has no attribute '__version__' 

### ISSUE THREAD

**Issue by mestia** [sciunto-org/python-bibtexparser#429]
**Describe the bug**
sphinx-build fails with `AttributeError: module 'bibtexparser' has no attribute '__version__'`

**Reproducing**

Version: `2.0.0b4`

Code:
```
cd /tmp/bibtexparser/docs && make html
make[2]: Entering directory '/tmp/bibtexparser/docs'
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v5.3.0              
                                   
Configuration error:               
There is a programmable error in your configuration file:
                                   
Traceback (most recent call last): 
  File "/usr/lib/python3/dist-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)          
  File "/tmp/bibtexparser/docs/source/conf.py", line 56, in <module>
    version = bp.__version__
AttributeError: module 'bibtexparser' has no attribute '__version__'

make[2]: *** [Makefile:45: html] Error 2
```

**Comment by MiWeiss** [comment]
Hi. 

Thanks a lot for your report?

Would you mind specifying in more detail the version your are using, i.e., are you working with the tagged version `2.0.0b4` of the current master branch (5b0157812138415d9333f737f4bd0b51e62d01f8), where the version is not yet bumped and thus still reported as `2.0.0b4` ? I am asking as some of the recent commits are related to the docs, and the master branch currently builds nicely on readthedocs.org.

**Comment by a-detiste** [comment]
same issue here

https://salsa.debian.org/python-team/packages/bibtexparser/-/jobs/5111893

**Comment by mestia** [comment]
Hi,

I can reproduce the problem with both tagged version 2.0.0b4 and the current master branch (https://github.com/sciunto-org/python-bibtexparser/commit/5b0157812138415d9333f737f4bd0b51e62d01f8)

For example:

 ```
cd /tmp && git clone https://github.com/sciunto-org/python-bibtexparser
cd /tmp/python-bibtexparser
python3 -c "import bibtexparser; print(bibtexparser.__file__)"
/tmp/python-bibtexparser/bibtexparser/__init__.py
python3 -c "import bibtexparser; print(bibtexparser.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'bibtexparser' has no attribute '__version__'
```

**Comment by MiWeiss** [comment]
Hi @mestia  and @a-detiste 

Thanks for the report. I am quite in a hurry but just merged a quick fix which should resolve this. 
The bug was quite stupid, not sure if/how this has ever worked :-P

I did not spend time on extensive testing for this, please do not hesitate to create a new issue if further problems pop up.
