### ISSUE TITLE
[QUESTION] bibtexparser 2 in Debian

### ISSUE THREAD

**Issue by jgpallero** [sciunto-org/python-bibtexparser#600]
Hello:

In the repositories if Debian Sid there is a package called python3-bibtexparser marked with version "2.0.0b5+really1.4.4-". With this strange version number I conclude that the actual version is 1.4.4, fact that is confirmed as after running a script I obtain 

`AttributeError: module 'bibtexparser' has no attribute 'parse_file'`

Is it planned to release in the near future the version 2 and upload to Debian?

**Comment by pemsley** [comment]
+1

**Comment by MiWeiss** [comment]
Yeah, that has been a mixup. If i recall correctly, version 1.4.4 was by mistake released as 2.0.0b5. This release should best be ignored. 

I am working on the 2.0.0 release right now. No promises, but I guess I'll soon jump over my shadow

**Comment by jgpallero** [comment]
Thank you for your work. Bibtexparser is a nice piece of software
